production:
  adapter: postgresql
  database: page_views_prod
  username: deploy
  password: n3xtm0v3m3nt
  encoding: utf8

development:
  adapter: postgresql
  database: page_views_dev
  username: arachman
  password:
  encoding: utf8

test:
  adapter: postgresql
  database: page_views_test
  username: arachman
  password:
  encoding: utf8
