development:
  adapter: postgresql
  database: page_views_dev
  username: arachman
  password:
  encoding: utf8

test:
  adapter: postgresql
  database: page_views_test
  username: arachman
  password:
  encoding: utf8
